<?php
/**
 * Hand-maintained asset manifest for the filters block editor script.
 *
 * The editor script is plain JavaScript (wp.* globals, no JSX/build step), so
 * this file is authored by hand instead of generated by @wordpress/scripts.
 * Keep the dependency list in sync with the wp.* namespaces index.js reads.
 *
 * @package Wb_Ajax_Filter
 */

return array(
	'dependencies' => array(
		'wp-blocks',
		'wp-element',
		'wp-block-editor',
		'wp-components',
		'wp-i18n',
		'wp-server-side-render',
	),
	'version'      => '1.2.2',
);
